# Generated by Django 2.2 on 2026-06-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('translator', '0005_delete_evaldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimPendingAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_code', models.CharField(db_index=True, max_length=255)),
                ('persona_name', models.CharField(max_length=255)),
                ('step', models.IntegerField(db_index=True)),
                ('action_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_code', models.CharField(db_index=True, max_length=255)),
                ('step', models.IntegerField()),
                ('environment', models.TextField(default='{}')),
                ('movement', models.TextField(default='{}')),
                ('is_movement_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('sim_code', 'step')},
            },
        ),
    ]
